### ISSUE TITLE
Entrevista

### ISSUE THREAD

**Issue by christopheremv** [SistemasTecTlaxiaco/entrevista-team-pro#1]
Audio de la entrevista:
https://drive.google.com/drive/folders/1BJ2DsPW9JFpP5_GoyHc4Z_YszdEzCddQ?usp=sharing

Reporte de la entrevista:
[reporte entrevista.pdf](https://github.com/SistemasTecTlaxiaco/entrevista-team-pro/files/7151652/reporte.entrevista.pdf)

**Comment by IsraelNicolas61** [comment]
Faltaron algunas preguntas acerca del tema.
Calificación 15/20 puntos

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
